# Generated by Django 4.1 on 2022-08-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('sahifa', models.PositiveSmallIntegerField()),
                ('janr', models.CharField(blank=True, choices=[('Hujjatli', 'Hujjatli'), ('Detektiv', 'Detektiv'), ('Sayohat', 'Sayohat'), ('Ilmiy', 'Ilmiy')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('jins', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
                ('tirik', models.BooleanField()),
                ('tugilgan_yil', models.DateField(blank=True, null=True)),
                ('kitoblar_soni', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('st_raqam', models.CharField(max_length=30, unique=True)),
                ('guruh', models.CharField(max_length=30)),
                ('bitiruvchi', models.BooleanField()),
                ('kitob_soni', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ol_sana', models.DateTimeField(auto_now_add=True)),
                ('qaytarilgan_sana', models.DateField(blank=True, null=True)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kutbxonachi.kitob')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kutbxonachi.student')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kutbxonachi.muallif'),
        ),
    ]
